services:
  db:
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=password
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./grafana/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"

  api:
    build: backend
    profiles:
      - backend
    command:
      - --dburl=postgres://todo:password@db/todo?sslmode=disable
      - --host=0.0.0.0
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - USER=backend
    ports:
      - 127.0.0.1:8080:8080

  simulate-ui:
    build: frontend
    profiles:
      - simulate-traffic
    environment:
      - DEBUG
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://tempo:4317/v1/traces

volumes:
  pgdata: {}
